name: testing

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: "Setup nightly toolchain"
        run: |
          rustup default nightly

      - name: "Test example server"
        run: |
          cargo run -- --verbose server init -m 1.20.4 -l paper
          cargo run -- --verbose plugin add simple-voice-chat -o
          cargo run -- --verbose plugin add chunky -p hangar -v 1.3.92

          mkdir another-server && cd another-server
          cp ../mup.lock .

          cargo run -- --verbose server install
          cargo run -- --verbose plugin remove simple-voice-chat --remove-orphans
